* Plan C

** A time accounting web app (mostly for musicians)

*** Introduction
This application tracks time spend on activities by providing data
input for instrument and time practiced as well as for non musician
related events, such as household chores and engineering tasks. In the
case of musical practice entries, graphs are produced.

** Multi-user
The app multi-user and requires users to login.

*** Installation
**** Requirements
PostgreSQL --Plan C uses the user-id of the process that runs racket.
             that user (probably you) must exist in Postgres with
	     a default database.  No password is used, but one can be
	     configured in config/planc-cfg.scm.
Racket (see /Caveats/ below.)

**** Procedure
1. Git clone
2. Use htpasswd (from Apache) to add a user to the password file (currently in the config dir as config/htpasswd)
3. Check the config file: config/planc-cfg.scm
   If you wish to run in devel (vs production) mode, create the file "devel".
   Run the file http-server.rkt (with DrRacket or racket.)

*** Usage
3. Browse  http://localhost:8008/ (production mode). Use port 8000 for /devel/ mode.
   
***** Caveats
You will have to install the following Racket packages in order to run the app:
 canonicalize-path
 collections
 date
 debug
 fmt
 seq 
 simple-svg
 yaml

Only tested on Gentoo GNU/Linux
