* The Plan

** Current design, repair and enhancement strategies
*** PENDING Save form data to disk after agregating changes.
1. Saving is done, but decided to save before agregation, so 
   more detail is preserved. This was done be accident, but 
   the result seems better than the original [no pun ] plan.
   
*** PENDING If saved data exists in a recent file, use it rather than the original
    file on disk. -- #'retrive-plan-c
*** PENDING Save new daily data to seperate file directories on disk
    If the current date is newer than that of the saved data,
    stash the disk data to history; start with fresh values
    for today. -- #'retrieve-plan-c

** FIXME
*** Critical
**** TODO Activities are definately disapearing from the WWW display
     1. After entry, some previous entries dissapear. Mon 10:04:39
     2. In the database, it seems the missing value (time-duration) 
        was assigned to  the wrong activity
**** TODO Crashes if ':' is missig from input timesring.
**** DONE Crash on input of hours
- Adding 1 hr of time to an existing crashes the response.
  #f instead of number was the errr.


*** Bad
**** TODO Upon  1st entry activites (probably the "0:00" ones) dissapear from form.
   + Upon adding missing activities, they apear at top of form,
     not in alpahbetical order.Aparently display is alphabetical order, but form is canonical.
     Decide on with to use in both places.
*** Anoying
**** Often it seems that WWW-form input is not excepted and needs to be repeated.

*** Cosmetic
**** TODO Make form-label text bold.

*** TODO Wish List 
**** STARTED Make the amount of detail displayed adjustable
     It was not anticipated, but by saving data as ativites rather thanas  plans, more
     detail is available (the date and time and any repetitions of an activity are
       now available.  
      1. It would be nice to provide a version of the display with like 
         activities agregated. As the display with the new detail is now 
	 different but still intersting.
      2. An ability to show all detail includeint times activer were peformet 
         is  also desired.
