* The Plan

** Current design, repair and enhancement strategies
*** DONE Save form data to disk after agregating changes.
1. Saving is done, but decided to save before agregation, so 
   more detail is preserved. This was done be accident, but 
   the result seems better than the original [no pun ] plan.
   
*** DONE If saved data exists in a recent file, use it rather than the original
    file on disk. -- #'retrive-plan-c
*** DONE Save new daily data to seperate file directories on disk
    If the current date is newer than that of the saved data,
    stash the disk data to history; start with fresh values
    for today. -- #'retrieve-plan-c

** FIXME
*** Critical
**** TODO Activities are definately disapearing from the WWW display
     1. After entry, some previous entries dissapear. Mon 10:04:39
     2. In the database, it seems the missing value (time-duration) 
        was assigned to  the wrong activity
**** TODO Crashes if ':' is missig from input timesring.
     1. Also fails on '::' - to many colons.
     2. (note: add validation 1st to the server, then to the client)
         validation need to occur before storage.

**** DONE Crash on input of hours
- Adding 1 hr of time to an existing crashes the response.
  #f instead of number was the errr.


*** Bad
**** Redirect/get is not correct--sends the page to nowhere.
     I want to redirect back the start page.
*** Anoying
**** DONE Often it seems that WWW-form input is not excepted and needs to be repeated.
     Fixed by adding a conifmation dialog.  No posts can happen without consent.
**** Filter out inputs > 16 hrs in the validation.  Just entered 30:00 instead of 0:30.


*** Cosmetic
**** TODO Make form-label text bold.


*** Wish List
**** STARTED Make the amount of detail displayed adjustable
     It was not anticipated, but by saving data as ativites rather thanas  plans, more
     detail is available (the date and time and any repetitions of an activity are
       now available.  
      1. It would be nice to provide a version of the display with like 
         activities agregated. As the display with the new detail is now 
	 different but still intersting.
      2. An ability to show all detail includeint times activer were peformet 
         is  also desired.
**** Add time of day to page
**** Add total time to page
**** Add a Notes sub valute to Activitie
**** Expand the mutiple-instrument fields in music practice


