---
#title = "Plan C Category and Groups declarations"

Fitness:
- Dance
- Other
- Pull-Ups
- Sleep
- Walking
- Yoga

Maitenance: 
- Clean House
- Kitchen:Cooking
- Laundry
- Misc
- Instrument Maint.  
- SSS

Life: [ "Social Entertainment", "Social Other" ]

Media: [ Movies/AV, News, Social, Study ]

Music Practice:
- Cello
- Clarinet
- Flute
- Guitar
- Other
- Percussion
- Piano/Kbd
- Recorder
- Trombone
- Trumpet/Flgl
- Voice

PIM: [ Finance, Planning ]

Engineering : [ CM, Design, PM, Programming, Study, SysAdm, Testing ]
