---
#title = "Plan C Category and Groups declarations"

Fitness:
- Dance
- Other
- Pull-Ups
- Sleep
- Walking
- Yoga

Maitenance: 
- Clean House
- Instrument Maint.  
- Kitchen:cook/clean
- Laundry
- Misc
- SSS

Life: [ "Social Entertainment", "Social Other" ]

Media: [ Movies/AV, News, Social, Study ]

Music Practice:
- Cello
- Clarinet
- Dance
- Flute
- Guitar
- Other
- Percussion
- Piano/Kbd
- Recorder
- Trombone
- Trumpet/Flgl
- Voice

PIM: [ Finance, Planning, SysAdm ]

Special Interest: [ CM, Engineering, Programming, Testing ]
