---
#title = "Plan C Category and Groups declarations"

Fitness:
- Dance
- Other
- Pull-Ups
- Sleep
- Walking
- Yoga

Maitenance: 
- Clean House
- Laundry
- Misc
- Instrument Maint.  

Life: [ "Cooking", "Sleep", "SSS", "Social Entertainment", "Social Other" ]

Media: [ Movies/AV, News, Research, Social, Study ]

Music Practice:
- Cello
- Clarinet
- Flute
- Guitar
- Other
- Percussion
- Piano/Kbd
- Recorder
- Trombone
- Trumpet/Flgl
- Voice

PIM: [ Finance, Planning ]

Engineering : [ CM, Debug, Design, ProjMgmt, Programming, Study, SysAdm, Testing ]
