(plan C 2022-03-28
        ((Fitness (Yoga 0:00)(Walking 0:00)(Pull-Ups 0:00)(Dance 0:00))
          (|Music Practice| (Cello/Guitar/Piano)
                            (Trombone/Trumpet/Flugelhorn)
                            (Clarinet/Flute/Recorder)
                            (Voice/Percussion/Dance))
          (Maintenance (SSS 0:00) (Kitchen:cook/clean 0:00)
                       (|Clean House|)(Laundry) (|Instrument Maint.|))
          (Media (News 0:00) (Social 2:00))
          (PIM (Planning 0:10) (SysAdm 15:30))
          (|Special Interest|) ))
