// This file is generated by ../lib/generate-js.rkt
export const Categories = ['Maitenance', 'Fitness', 'Media', 'Music Practice', 'PIM', 'Special Interest'];

export const ActionsByCatIx=[['SSS', 'Kitchen:cook/clean', 'Clean House', 'Laundry', 'Instrument Maint.'],
  ['Yoga', 'Walking', 'Pull-Ups', 'Dance'],
  ['News', 'Social', 'Movies/AV'],
  ['Cello/Guitar/Piano', 'Trombone/Trumpet/Flugelhorn', 'Clarinet/Flute/Recorder', 'Voice/Percussion/Dance'],
  ['Planning', 'SysAdm'],
  ['Programming']];

